version: "3.6"

services:
  github-contributors-action:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: github-contributors-action
    environment:
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
      - SOURCE_GITHUB_REPOSITORY=hyperledger-tooling/github-contributors-action
      - CONTRIBUTORS_SECTION_PATTERN=## Contributors
      - CONTRIBUTORS_SECTION_END_PATTERN=## Contributions
      - INPUT_TEMPLATE_FILE=/assets/minimal.md
      - FILE_WITH_PATTERN=/README.md
    volumes:
      - ../assets:/assets
      - ../README.md:/README.md
