version: "3.6"

networks:
  test_network:
    name: test_network

services:
  github-contributors-action:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-contributors-action
    environment:
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
      - GITHUB_REPOSITORY=arsulegai/github-contributors-action
      - CONTRIBUTORS_SECTION_PATTERN=# Contributors
      - CONTRIBUTORS_SECTION_END_PATTERN=## Contributions
      - INPUT_TEMPLATE_FILE=/templates/minimal.md
      - FILE_WITH_PATTERN=/README.md
    volumes:
      - ./templates:/templates
      - ./README.md:/README.md
    networks:
      - test_network
